In [6]:
pip install requests selenium beautifulsoup4 -q

Note: you may need to restart the kernel to use updated packages.

In [80]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
import time
import json
import pandas as pd

In [104]:
driver = webdriver.Chrome() # 웹 창 생성
driver.maximize_window() # 웹 창 최대화
driver.get('https://shopping.naver.com/home') # 특정 url 웹사이트 이동
driver.implicitly_wait(1) # 정보를 받아오는 시간

path = '//*[@id="gnb-gnb"]/div[2]/div/div[2]/div[1]/form/div/div/div/div/input' #XPATH는 도달하기까지의 경로를 의미
search_word = '모자'

search_box = driver.find_element(By.XPATH, path) # 변수 내에서 설정한 path 내에 XPATH가 있음을 의미
search_box.clear() # 창 비워줌(예외 처리)   
search_box.send_keys(search_word) # 검색어 입력
search_box.send_keys(Keys.ENTER) # 검색 실행

# last_height = driver.execute_script("return document.body.scrollHeight") # 스크롤 내리고 높이 측정

# for _ in range(10):
#     driver.execute_script("window.scrollTo(0, document.body.scrollHeight);") # 스크롤 내리기
#     time.sleep(1) # 스크롤 내리고 1초 대기
#     new_height = driver.execute_script("return document.body.scrollHeight") # 스크롤 내리고 높이 측정
    
#     print(_)
#     # if new_height == last_height: # 스크롤 내리고 높이가 변화가 없으면 멈춤
#     #     break
    
#     # last_height = new_height # 스크롤 내리고 높이가 변화가 있으면 높이 저장
# print(driver.page_source)

items_path = '//*[@id="composite-card-list"]/div/ul[1]/li'
items = driver.find_elements(By.XPATH, items_path)

results = []
for item in items:
    try:
        contents = item.find_element(By.CSS_SELECTOR, 'div > a').get_attribute('data-shp-contents-dtl')
        cont_dict = json.loads(contents)
        for cont in cont_dict:
            if cont['key'] == 'prod_nm':
                prod_name = cont['value']
            if cont['key'] == 'price':
                price = cont['value']
                
        results.append((prod_name, price))
    except NoSuchElementException:
        print("NoSuchElementException")

driver.quit()

df = pd.DataFrame(results, columns=['prod_name','price'])
df["price"] = df["price"] + "원"
    
    # print(cont, type(cont))

NoSuchElementException
NoSuchElementException
NoSuchElementException

In [105]:
df

                                            prod_name   price
0                        [MLB] 루키 언스트럭쳐 볼캡 (18 COLOR)  36000원
1                      [MLB] 베터 플렉스 스트럭쳐 볼캡 NY (Navy)  33000원
2                       [MLB] 에이스 언스트럭쳐 볼캡 (14 COLOR)  36000원
3              [MLB] 루키 언스트럭쳐 볼캡 NY (Beige) 3ACP7701N  36000원
4                       [MLB] 에이스 언스트럭쳐 볼캡 (14 COLOR)  36000원
5                        [MLB] 루키 언스트럭쳐 볼캡 (18 COLOR)  36000원
6                  탄탄한 린넨 여성 봄 여름 벨크로 보넷 벙거지모자 여자 버킷햇  14800원
7      여름모자 챙넓은모자 여성 휴양지 바캉스 비치 여행 산책 와이드챙 버킷햇 벙거지 모자  18900원
8                           여성 UV차단모자 라탄 자외선 차단 썬캡 모자   8990원
9                 국산 썬캡 자외선차단모자 햇빛 uv a b99.9%차단 여자남성  11900원
10           나이키 모자 러닝 대두 빅사이즈 테니스 마라톤 운동 드라이핏 트레일 볼캡  38900원
11            라피아햇 여름버킷햇 밀짚모자 여성 챙넓은 비치 바캉스 휴양지 명품 모자  11900원
12                      텐지 VDN 프리미엄 볼캡 얼굴작아보이는 깊은 캡모자  38000원
13     여름모자 밀짚모자 챙넓은 휴양지 라피아 라탄 대두 여성벙거지모자 소유진 보넷 버킷햇  15900원
14                                 폴로 캡 모자 랄프로렌 볼캡 치노  67900원
15                    아이더세이프티 쿨링 썬가드 모자 햇빛 가리개 자외선 차단  12000원
16                      아디다스 나이키 모자 러닝 마라톤 빅사이즈 대두 볼캡  29500원
17               국내제작 UV 99.9프로 자외선 차단 썬캡 이보영 키 날개 선캡  19400원
18                    [MLB] 베이직 워싱 언스트럭쳐 볼캡 (3 COLOR)  39000원
19              [MLB] 루키 언스트럭쳐 볼캡 LA (Blue) 3ACP7701N  36000원
20                          클래식 캡모자 여성 남성 여름 패션 여름 모자  21500원
21                                VA 스터드 피그먼트 버킷햇 스카이  33150원
22         [샤이니 키 착용] [33차 리오더] 린에비뉴 피그먼트 볼캡 시그니쳐 그레이  39000원
23  햇빛 자외선차단모자 농사 모자 작업 일 여름 남자여자 썬캡 성인 물놀이 플랩캡 햇볕가리개   6300원
24                             썬캡모자 테니스 슬라이드 남자 여성 썬캡   6700원
25               숏캡 숏챙모자 챙짧은 트레일 러닝 마라톤 대두 빅사이즈 모자 볼캡  10700원
26      여름모자 챙넓은모자 여성 휴양지 바캉스 비치 여행 밀짚 산책 라피아햇 벙거지 모자  15890원
27          나이키 아디다스 버킷햇 여자 남자 벙거지 모자 겨울 캠핑 서핑 정글 챙모자  24500원
28                    연예인 명품 남자 모자 대두 볼캡 XXL 빅사이즈 캡모자  18500원
29      [MLB] 데미지 워싱 데님 언스트럭쳐 볼캡 NY (Black) 3ACPVD34N  49000원
30                  아디다스 에어로레디 라이트웨이트 캡 스포츠 모자 테니스 러닝  25000원
31                 [MLB] BEST 루키/에이스 언스트럭쳐 볼캡 28종 택 1  36000원
32            [MLB] 바시티 빈티지 컬시브 배색 언스트럭쳐 볼캡 (4 COLOR)  43000원
33         나이키 모자 헤리티지 86 클럽 러닝 대두 퓨추라 스우시 드라이핏 데님 볼캡  26900원
34       챙넓은모자 여성 버킷햇 자외선 햇빛 차단 벙거지 바캉스 휴양지 등산 물놀이 모자   9900원
35  NYC 모자 볼캡 러닝 마라톤 테니스 헬스 운동 물놀이 워터파크 방수캡 빅사이즈 여...   6900원
36       자외선차단모자 썬바이저 썬캡 햇빛 성인 물놀이 플랩캡 농사 햇볕가리개 창넓은모자   7900원
37  나이키 모자 대두 빅사이즈 (60호XL)포함 여자 남자 드라이핏 야구 볼 캡 골프 버킷햇  25900원
38      아디다스 나이키 썬캡 여름 모자 썬바이저 테니스 러닝 여성 남성 자외선 햇빛 차단  19900원
39                         MLB모자 47브랜드 LA다저스 NY 볼캡 모자  28900원
40                        왕대두 대두 볼캡 빅사이즈 남자 여자 야구 캡모자   5500원
41       챙넓은 남자 여성 여름 버킷햇 벙거지 휴양지 비치 여행 사파리 물놀이 정글 모자  19800원
42                     숏캡 숏챙모자 챙짧은 트레일 러닝 등산 캠핑 모자 볼캡   8700원
43  자외선차단모자 썬캡 성인 물놀이 플랩캡 농사 작업 일 햅볕가리개 남자 여자 빅사이즈 모자   6300원
44                       호카 모자 러닝 퍼포먼스 트레일 마라톤 팩커블 볼캡  52700원
45       국내제작 초경량 45g 블랙타공 러닝모자 UV차단 기능성소재 트레일 마라톤 볼캡  29750원
46  [매장판] 나이키 ACG 트레일 아웃도어 캡 블랙 모자 M/L FB6533-010 297  49500원

In [106]:
df['color'] = df['prod_name'].str.extract(r'(?i)(\d+)\s*color', expand=False).fillna('0').astype(int)

In [107]:
df

                                            prod_name   price  color
0                        [MLB] 루키 언스트럭쳐 볼캡 (18 COLOR)  36000원     18
1                      [MLB] 베터 플렉스 스트럭쳐 볼캡 NY (Navy)  33000원      0
2                       [MLB] 에이스 언스트럭쳐 볼캡 (14 COLOR)  36000원     14
3              [MLB] 루키 언스트럭쳐 볼캡 NY (Beige) 3ACP7701N  36000원      0
4                       [MLB] 에이스 언스트럭쳐 볼캡 (14 COLOR)  36000원     14
5                        [MLB] 루키 언스트럭쳐 볼캡 (18 COLOR)  36000원     18
6                  탄탄한 린넨 여성 봄 여름 벨크로 보넷 벙거지모자 여자 버킷햇  14800원      0
7      여름모자 챙넓은모자 여성 휴양지 바캉스 비치 여행 산책 와이드챙 버킷햇 벙거지 모자  18900원      0
8                           여성 UV차단모자 라탄 자외선 차단 썬캡 모자   8990원      0
9                 국산 썬캡 자외선차단모자 햇빛 uv a b99.9%차단 여자남성  11900원      0
10           나이키 모자 러닝 대두 빅사이즈 테니스 마라톤 운동 드라이핏 트레일 볼캡  38900원      0
11            라피아햇 여름버킷햇 밀짚모자 여성 챙넓은 비치 바캉스 휴양지 명품 모자  11900원      0
12                      텐지 VDN 프리미엄 볼캡 얼굴작아보이는 깊은 캡모자  38000원      0
13     여름모자 밀짚모자 챙넓은 휴양지 라피아 라탄 대두 여성벙거지모자 소유진 보넷 버킷햇  15900원      0
14                                 폴로 캡 모자 랄프로렌 볼캡 치노  67900원      0
15                    아이더세이프티 쿨링 썬가드 모자 햇빛 가리개 자외선 차단  12000원      0
16                      아디다스 나이키 모자 러닝 마라톤 빅사이즈 대두 볼캡  29500원      0
17               국내제작 UV 99.9프로 자외선 차단 썬캡 이보영 키 날개 선캡  19400원      0
18                    [MLB] 베이직 워싱 언스트럭쳐 볼캡 (3 COLOR)  39000원      3
19              [MLB] 루키 언스트럭쳐 볼캡 LA (Blue) 3ACP7701N  36000원      0
20                          클래식 캡모자 여성 남성 여름 패션 여름 모자  21500원      0
21                                VA 스터드 피그먼트 버킷햇 스카이  33150원      0
22         [샤이니 키 착용] [33차 리오더] 린에비뉴 피그먼트 볼캡 시그니쳐 그레이  39000원      0
23  햇빛 자외선차단모자 농사 모자 작업 일 여름 남자여자 썬캡 성인 물놀이 플랩캡 햇볕가리개   6300원      0
24                             썬캡모자 테니스 슬라이드 남자 여성 썬캡   6700원      0
25               숏캡 숏챙모자 챙짧은 트레일 러닝 마라톤 대두 빅사이즈 모자 볼캡  10700원      0
26      여름모자 챙넓은모자 여성 휴양지 바캉스 비치 여행 밀짚 산책 라피아햇 벙거지 모자  15890원      0
27          나이키 아디다스 버킷햇 여자 남자 벙거지 모자 겨울 캠핑 서핑 정글 챙모자  24500원      0
28                    연예인 명품 남자 모자 대두 볼캡 XXL 빅사이즈 캡모자  18500원      0
29      [MLB] 데미지 워싱 데님 언스트럭쳐 볼캡 NY (Black) 3ACPVD34N  49000원      0
30                  아디다스 에어로레디 라이트웨이트 캡 스포츠 모자 테니스 러닝  25000원      0
31                 [MLB] BEST 루키/에이스 언스트럭쳐 볼캡 28종 택 1  36000원      0
32            [MLB] 바시티 빈티지 컬시브 배색 언스트럭쳐 볼캡 (4 COLOR)  43000원      4
33         나이키 모자 헤리티지 86 클럽 러닝 대두 퓨추라 스우시 드라이핏 데님 볼캡  26900원      0
34       챙넓은모자 여성 버킷햇 자외선 햇빛 차단 벙거지 바캉스 휴양지 등산 물놀이 모자   9900원      0
35  NYC 모자 볼캡 러닝 마라톤 테니스 헬스 운동 물놀이 워터파크 방수캡 빅사이즈 여...   6900원      0
36       자외선차단모자 썬바이저 썬캡 햇빛 성인 물놀이 플랩캡 농사 햇볕가리개 창넓은모자   7900원      0
37  나이키 모자 대두 빅사이즈 (60호XL)포함 여자 남자 드라이핏 야구 볼 캡 골프 버킷햇  25900원      0
38      아디다스 나이키 썬캡 여름 모자 썬바이저 테니스 러닝 여성 남성 자외선 햇빛 차단  19900원      0
39                         MLB모자 47브랜드 LA다저스 NY 볼캡 모자  28900원      0
40                        왕대두 대두 볼캡 빅사이즈 남자 여자 야구 캡모자   5500원      0
41       챙넓은 남자 여성 여름 버킷햇 벙거지 휴양지 비치 여행 사파리 물놀이 정글 모자  19800원      0
42                     숏캡 숏챙모자 챙짧은 트레일 러닝 등산 캠핑 모자 볼캡   8700원      0
43  자외선차단모자 썬캡 성인 물놀이 플랩캡 농사 작업 일 햅볕가리개 남자 여자 빅사이즈 모자   6300원      0
44                       호카 모자 러닝 퍼포먼스 트레일 마라톤 팩커블 볼캡  52700원      0
45       국내제작 초경량 45g 블랙타공 러닝모자 UV차단 기능성소재 트레일 마라톤 볼캡  29750원      0
46  [매장판] 나이키 ACG 트레일 아웃도어 캡 블랙 모자 M/L FB6533-010 297  49500원      0

In [108]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
from bs4 import BeautifulSoup
import requests
import time
import json
import pandas as pd

driver = webdriver.Chrome()
driver.maximize_window()
driver.get('https://www.naver.com')